# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180417_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contenttypes.ContentType', verbose_name='关联普通课或者学位课表'),
        ),
    ]
