# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_types', to='contenttypes.ContentType', verbose_name='关联普通课或者学位课表'),
        ),
        migrations.AlterField(
            model_name='userauthtoken',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
