# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('datasource', '0002_auto_20180418_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答')),
                ('agree_number', models.IntegerField(default=0, verbose_name='点赞数')),
                ('disagree_number', models.IntegerField(default=0, verbose_name='点踩数')),
                ('answer_date', models.DateTimeField(auto_now=True, verbose_name='日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account', verbose_name='回答者')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=512, verbose_name='评论内容')),
                ('attachment_path', models.CharField(blank=True, help_text='跟进记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account', verbose_name='评论者')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Answer')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.AnswerComment', verbose_name='基于评论的评论')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='活动名称')),
                ('brief', models.TextField(verbose_name='优惠券介绍')),
                ('coupon_type', models.SmallIntegerField(choices=[(1, '通用券'), (2, '满减券'), (3, '折扣券')], default=1, verbose_name='券类型')),
                ('money_equivalent_value', models.IntegerField(default=0, verbose_name='等值货币（通用和满减券时可抵扣的钱）')),
                ('off_percent', models.PositiveSmallIntegerField(blank=True, help_text='只针对折扣券，例7.9折，写79', null=True, verbose_name='折扣百分比')),
                ('minimum_consume', models.PositiveIntegerField(default=0, help_text='仅在满减券时填写此字段', verbose_name='最低消费')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='可以把优惠券跟课程ID绑定', null=True, verbose_name='绑定课程')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量(张)')),
                ('open_date', models.DateField(verbose_name='优惠券领取开始时间')),
                ('close_date', models.DateField(verbose_name='优惠券领取结束时间')),
                ('valid_begin_date', models.DateField(blank=True, null=True, verbose_name='有效期开始时间')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='有效结束时间')),
                ('coupon_valid_days', models.PositiveIntegerField(blank=True, help_text='自券被领时开始算起', null=True, verbose_name='优惠券有效期（天）')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='优惠券关联的表（普通课程）')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='优惠券唯一标识')),
                ('status', models.SmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1)),
                ('get_time', models.DateTimeField(help_text='用户领取时间', verbose_name='领取时间')),
                ('used_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account', verbose_name='拥有者')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_company', models.CharField(max_length=64, verbose_name='公司')),
                ('current_position', models.CharField(max_length=64, verbose_name='职位')),
                ('current_salary', models.IntegerField(verbose_name='薪资')),
                ('work_experience', models.IntegerField(verbose_name='工作经验')),
                ('open_module', models.BooleanField(default=True, verbose_name='是否开通第1模块')),
                ('stu_specified_mentor', models.CharField(blank=True, max_length=32, null=True, verbose_name='学员自行指定的导师名')),
                ('study_plan', models.SmallIntegerField(choices=[(1, '1-2小时/天'), (2, '2-3小时/天'), (3, '3-5小时/天'), (4, '5小时+/天')], default=1)),
                ('why_take_this_course', models.TextField(max_length=1024, verbose_name='报此课程原因')),
                ('why_choose_us', models.TextField(max_length=1024, verbose_name='为何选路飞')),
                ('your_expectation', models.TextField(max_length=1024, verbose_name='你的期待')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='购买课程时间')),
                ('valid_begin_date', models.DateField(verbose_name='有效期开始自')),
                ('valid_end_date', models.DateField(verbose_name='有效期结束至')),
                ('status', models.SmallIntegerField(choices=[(1, '已开通'), (2, '已过期')], default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledDegreeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='购买课程时间')),
                ('valid_begin_date', models.DateField(blank=True, help_text='开通模块时再设置有效期', null=True, verbose_name='有效期开始自')),
                ('valid_end_date', models.DateField(blank=True, null=True, verbose_name='有效期结束至')),
                ('study_status', models.SmallIntegerField(choices=[(1, '在学中'), (2, '休学中'), (3, '已毕业'), (4, '超时结业'), (5, '未开始')], default=5)),
                ('mentor_fee_balance', models.PositiveIntegerField(help_text='这个学员的导师费用，每有惩罚，需在此字段同时扣除', verbose_name='导师费用余额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account')),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.DegreeCourse')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_students', to='datasource.Account', verbose_name='导师')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (-1, 'D'), (0, 'N/A'), (-100, 'COPY')], null=True, verbose_name='分数')),
                ('mentor_comment', models.TextField(blank=True, null=True, verbose_name='导师批注')),
                ('status', models.SmallIntegerField(choices=[(1, '待批改'), (2, '已通过'), (3, '不合格')], default=1, verbose_name='作业状态')),
                ('submit_num', models.SmallIntegerField(default=0, verbose_name='提交次数')),
                ('correct_date', models.DateTimeField(blank=True, null=True, verbose_name='备注日期')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='作业提交日期')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='批改日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='提交日期')),
                ('reward_status', models.SmallIntegerField(default=1, verbose_name='作业记录奖惩状态')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Homework')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_stu_homework_record', to='datasource.Account', verbose_name='导师')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.EnrolledDegreeCourse', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=128, unique=True, verbose_name='订单唯一标识（自动生成）')),
                ('payment_type', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '优惠码'), (4, '贝里')])),
                ('actual_amount', models.FloatField(verbose_name='实付金额')),
                ('payment_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='支付第3方订单号')),
                ('status', models.SmallIntegerField(choices=[(1, '交易成功'), (2, '待支付'), (3, '退费申请中'), (4, '已退费'), (5, '主动取消'), (6, '超时取消')], verbose_name='状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='订单取消时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联课程或学位课程表中的课程ID')),
                ('original_price', models.FloatField(verbose_name='课程原价')),
                ('price', models.FloatField(verbose_name='折后价格')),
                ('valid_period_display', models.CharField(help_text='用于页面上显示', max_length=32, verbose_name='有效期显示')),
                ('valid_period', models.PositiveIntegerField(help_text='用于计算课程有效期', verbose_name='有效期(days)')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='其他说明')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联课程或学位课程表')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Order')),
            ],
        ),
        migrations.CreateModel(
            name='QACounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='问题或回答的ID')),
                ('data_type', models.SmallIntegerField(choices=[(1, '点赞'), (2, '踩'), (3, '同问')])),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='问题或回答表')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='问题概要')),
                ('question_type', models.SmallIntegerField(choices=[(1, '专题课程问题'), (2, '学位课程问题')], default=1, verbose_name='来源')),
                ('content', models.TextField(max_length=1024, verbose_name='问题内容')),
                ('enquiries_count', models.IntegerField(default=0, verbose_name='同问者计数')),
                ('attachment_path', models.CharField(blank=True, help_text='问题记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待解答'), (1, '已解答'), (2, '已关闭')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account', verbose_name='提问者')),
                ('course_section', models.ForeignKey(blank=True, help_text='针对整个学位课程的提问不需关联特定课时', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.CourseSection')),
                ('degree_course', models.ForeignKey(blank=True, help_text='若是针对整个学位课程的提问，关联这个', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.DegreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.IntegerField(verbose_name='金额(贝里)')),
                ('balance', models.PositiveIntegerField(verbose_name='奖金余额(贝里)')),
                ('maturity_date', models.DateField(help_text='每天凌晨定时任务会跑，所以最迟一天', verbose_name='成熟日期(可提现日期)')),
                ('applied', models.BooleanField(default=False, help_text='奖赏纪录是否已被执行', verbose_name='是否已被执行')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='事件生效日期')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='事件触发日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account', verbose_name='被执行人')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('degree_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.DegreeCourse', verbose_name='关联学位课程')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.SmallIntegerField(choices=[(1, '未按时交作业'), (2, '未及时批改作业'), (3, '作业成绩'), (4, '未在规定时间内对学员进行跟进'), (5, '未在规定时间内回复学员问题'), (6, '收到学员投诉'), (7, '导师相关'), (8, '学位奖学金')], verbose_name='积分规则')),
                ('score_type', models.SmallIntegerField(choices=[(1, '奖励'), (2, '惩罚'), (3, '初始分配')], verbose_name='奖惩')),
                ('score', models.IntegerField(help_text='扣分数与贝里相等')),
                ('memo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='开通日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('status', models.SmallIntegerField(choices=[(1, '在学'), (2, '未开通'), (3, '已完成')], default=1, verbose_name='状态')),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Course', verbose_name='学位模块')),
                ('enrolled_degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.EnrolledDegreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='StuFollowUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_tool', models.SmallIntegerField(choices=[(1, 'QQ'), (2, '微信'), (3, '电话'), (4, '系统通知')], default=1)),
                ('record', models.TextField(verbose_name='跟进记录')),
                ('attachment_path', models.CharField(blank=True, help_text='跟进记录的截图等', max_length=128, null=True, verbose_name='附件路径')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enrolled_degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.EnrolledDegreeCourse', verbose_name='学生')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='datasource.Account', verbose_name='导师')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金额')),
                ('balance', models.IntegerField(verbose_name='账户余额')),
                ('transaction_type', models.SmallIntegerField(choices=[(0, '收入'), (1, '支出'), (2, '退款'), (3, '提现')])),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象，如：某个订单ID、某项奖惩ID')),
                ('transaction_number', models.CharField(max_length=128, unique=True, verbose_name='流水号（为每一笔生成贝里交易生成唯一标识）')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联表，如：订单表、奖惩表')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scorerule',
            unique_together=set([('rule', 'score_type')]),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='score_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.ScoreRule', verbose_name='关联规则'),
        ),
        migrations.AddField(
            model_name='enrolleddegreecourse',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasource.OrderDetail', verbose_name='关联订单详细'),
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasource.OrderDetail', verbose_name='关联订单详细'),
        ),
        migrations.AddField(
            model_name='degreeregistrationform',
            name='enrolled_degree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasource.EnrolledDegreeCourse'),
        ),
        migrations.AddField(
            model_name='couponrecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.Order', verbose_name='关联订单（订单使用优惠券）'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasource.Question', verbose_name='问题'),
        ),
        migrations.AlterUniqueTogether(
            name='studyrecord',
            unique_together=set([('enrolled_degree_course', 'course_module')]),
        ),
        migrations.AlterUniqueTogether(
            name='qacounter',
            unique_together=set([('content_type', 'object_id', 'account')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('order', 'content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='homeworkrecord',
            unique_together=set([('homework', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='enrolleddegreecourse',
            unique_together=set([('account', 'degree_course')]),
        ),
    ]
